### ISSUE TITLE
An issue with K (steps) in training with lookaround

### ISSUE THREAD

**Issue by Mehrdad-Noori** [Ardcy/Lookaround#1]
First, I'd like to express my appreciation for your great work.

I have a question regarding changing the paramater K in train.py ('frequence' argument) using the lookaround optimizer. 
I used the default setting to run the code with Cifar10 dataset. More specifgicaly I am using the following:
`python train.py --yaml_path='resnet50_cifar10.yaml' --train_mode='TRAIN_LOOKAROUND' --cuda_id=0 --data_dir='dataset/' --out='./out/' --optimizer='Lookaround'
`

I tried to change the parameter K to 100 (I used --frequenc 100 in the above command), the trainig time for each epoch is the same and I get somehow similar results. I am wondering whether it is normal. Becase as I understand from the paper, K means how much steps we want to take using each augmentation before performing average. So if I increase it to 100 there shoud be a meaningful change in the results.

Could you please provide any insights into whether this behavior is expected under the circumstances described, or there is maybe something I am missing in the code.

Thank you for your time and assistance. I look forward to your response.

**Comment by Ardcy** [comment]
Thank you for your question.

I think that under cifar 10, using Lookaround optimizer（K=100） to train resnet50, this result is also acceptable.

In fact, k is not a carefully adjusted parameter. We adjusted it to 5 under cifar100 to get the best results (see figure 5 in the paper), and then extended it to all training processes.

The lookaround optimizer includes multiple different models. In a training cycle, different models will gradually move towards different areas in the loss space. When k is large, the distance between different models will increase. When k is too large, the parameters of different models cannot be averaged (the averaged model has almost 0 accuracy). But this k is actually relatively robust. Even if it is set to close to 10,000, this kind of thing will almost never happen.

If you are still confused, please continue to discuss this with me.

**Comment by Mehrdad-Noori** [comment]
Thank you very much for your respond. 
I completely understand it now about why the perfromance is similar. The only remaining thing is that I am not sure why each training iteration when we use for example k=1 takes exacly the same time compared to when we use k=10000. If I understand it correcty, in each around step, we should perform k optimization step (SGD-based) so we should expect a significant change in the training time when we switch from k=1 to k=10000.

**Comment by Ardcy** [comment]
Assume that training a model requires n epochs, and each epoch has m batches of data. Using Lookaround Optimizer requires training for y cycles.

In fact, it satisfies: n * m = y * k

As k increases, y becomes smaller. So, the total training time did not change.
